site_name: wAIk
site_description: Documentation for the wAIk gait analysis project
docs_dir: docs
site_url: https://bivanjeAI-wAIk.github.io/

theme:
  name: material

nav:
  - Home: Home.md
  - Project Specifications: Project-Specifications.md
  - Installation and Setup: Installation-and-Login.md
  - Use Cases: Use-Cases.md
  - Feature Documentation: Feature-Documentation.md
