name: Sync to Wiki
on:
  push:
    branches:
      - main

jobs:
  wiki-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: 'docs'
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
